export const contactCopy = {
  pt: {
    title: 'Ummundu — Contacto',
    label: 'Contacto',
    intro: 'Partilhe as suas intenções. Um primeiro gesto que clarifica o rumo.',
    fields: {
      departure: 'Partida',
      month: 'Mês',
      year: 'Ano',
      destination: 'Destino',
      duration: 'Duração',
      travellers: 'Viajantes',
      investment: 'Investimento',
      firstName: 'Nome',
      lastName: 'Apelido',
      email: 'Email',
      phone: 'Telefone',
      message: 'Mensagem',
    },
    months: [
      'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
      'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro',
    ],
    durations: ['7 dias', '8 dias', '9 dias', '10 dias', '11 dias', '12 dias', '13 dias', '14 dias', 'Mais de 14 dias'],
    travellerOptions: ['1 pessoa', '2 pessoas', '3 pessoas', '4 pessoas', '5 pessoas', '6 pessoas'],
    investmentOptions: ['Até 10.000€ por pessoa', '10.000€ a 25.000€ por pessoa', 'Mais de 25.000€ por pessoa'],
    requiredNote: '(*) Informação necessária',
    privacyPrefix: 'Os seus dados pessoais serão tratados para responder ao pedido. Consulte a ',
    privacyLinkLabel: 'Declaração de Privacidade',
    privacyLinkHref: '/privacidade',
    privacySuffix: ' para mais informações.',
    submit: 'Enviar',
    successRedirect: '/contacto/obrigado',
  },
  en: {
    title: 'Ummundu — Contact',
    label: 'Contact',
    intro: 'Share your intentions. A first note that clarifies the direction.',
    fields: {
      departure: 'Departure',
      month: 'Month',
      year: 'Year',
      destination: 'Destination',
      duration: 'Duration',
      travellers: 'Travellers',
      investment: 'Investment',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      message: 'Message',
    },
    months: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ],
    durations: ['7 days', '8 days', '9 days', '10 days', '11 days', '12 days', '13 days', '14 days', 'More than 14 days'],
    travellerOptions: ['1 person', '2 people', '3 people', '4 people', '5 people', '6 people'],
    investmentOptions: ['Up to €10,000 per person', '€10,000 to €25,000 per person', 'More than €25,000 per person'],
    requiredNote: '(*) Required information',
    privacyPrefix: 'Your personal data will be processed to respond to the request. Consult the ',
    privacyLinkLabel: 'Privacy Statement',
    privacyLinkHref: '/en/privacy',
    privacySuffix: ' for further information.',
    submit: 'Send',
    successRedirect: '/en/contact/success',
  },
};
